server:
  port: 9994

spring:
#  profiles:
#    active: dev
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
        driverClassName: com.mysql.cj.jdbc.Driver
#        driver-class-name: com.mysql.cj.jdbc.Driver
# 121.41.82.47
        platform: mysql
        url: jdbc:mysql://121.41.82.47:3306/wb20201216?useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: wb20201216
        password: wb20201216
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 86400
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        filters: stat,wall
        logSlowSql: true
  # 文件上传大小限制为 10MB
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  configuration:
    # 将sql打印到控制台（该配置会将sql语句和查询的结果都打印到控制台）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 是否开启自动驼峰命名规则映射，MP默认是开启的
    map-underscore-to-camel-case: true
  # 自动以SQL语句文件路径
  mapper-locations: classpath*:/mapper/**/*.xml
  # MP设置全局id策略为uuid，拒不设置id策略在实体类对象的id属性上设置(局部策略 优先于 全局策略)
  global-config:
    db-config:
      # 主键策略配置
      # id-type: uuid
      # 子弹验证策略配置
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_null
      # 表名前缀配置
      #table-prefix: sys_
  # mybatis的自定义配置
  # config-location: classpath:mybatis-config.xml   // config-location配置不可与configuration同时配置，否则启动时程序会报错
  # myBaits别名包扫描路径配置
  type-aliases-package: com.ethan.ryds.entity

prop:
#  windows
#  upload-folder: /upload/

# linux
  upload-folder: /upload/


file:
  # 上传的服务器上的映射文件夹
  accessPath: /upload/
  # 静态资源对外暴露的访问路径
  staticAccessPath: /upload/**
  #文件上传目录（注意Linux和 Windows上的目录结构不同）
  uploadFolder: /root/uploads/